// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    "graphqlEndpoint": process.env.REACT_APP_GQL_URL,
    "region": "us-east-2",
    "authenticationType": "API_KEY",
    "apiKey": process.env.REACT_APP_AWS_API_KEY,
};